name: Julia

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JULIA_CACHE: '1'
  JULIA_NUM_THREADS: 'auto'

jobs:
  build_test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Julia cache
      uses: actions/cache@v3
      continue-on-error: false
      if: ${{ env.JULIA_CACHE != '0'}}
      with:
        path: ~/.julia
        key: ${{ runner.os }}-julia-${{ hashFiles('**/Project.toml') }}
        restore-keys: |
          ${{ runner.os }}-julia-

    - name: Build and run docker image
      run: |
        docker build -t rinha . 2> build.log && docker run rinha
